const modules=['เวชปฏิบัติครอบครัวและชุมชน','การพยาบาลในชุมชน','ส่งเสริมสุขภาพทุกกลุ่มวัย','ป้องกันและควบคุมโรคและระบาดวิทยา','อาชีวอนามัยและความปลอดภัย','สุขาภิบาลและอนามัยสิ่งแวดล้อม','พัฒนาระบบบริการปฐมภูมิและเครือข่าย','อนามัยโรงเรียน','สุขภาพจิตและจิตเวชในชุมชน','บำบัดยาเสพติด สุรา บุหรี่','สุขศึกษาและพัฒนาพฤติกรรมสุขภาพ','จัดเก็บรายได้หน่วยบริการ','ข้อมูลคุณภาพ'];
const progress=[92,78,88,81,74,69,85,90,72,66,83,95,87];
let tasks=JSON.parse(localStorage.getItem('pcTasks')||'[]');
if(!tasks.length)tasks=[{name:'ติดตามผู้ป่วย Home Visit',module:modules[1],owner:'ทีม COC',due:'',status:'กำลังดำเนินการ'},{name:'สอบสวนโรคไข้เลือดออก',module:modules[3],owner:'SRRT',due:'',status:'เร่งด่วน'},{name:'ประเมินโรงเรียนส่งเสริมสุขภาพ',module:modules[7],owner:'ทีมส่งเสริมฯ',due:'',status:'เสร็จสิ้น'},{name:'รายงานตัวชี้วัด NCD',module:modules[12],owner:'ทีม Data',due:'',status:'รอติดตาม'}];
const content=document.getElementById('content'),title=document.getElementById('pageTitle');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function save(){localStorage.setItem('pcTasks',JSON.stringify(tasks))}function badge(s){let c=s==='เสร็จสิ้น'?'done':s==='เร่งด่วน'?'urgent':s==='รอติดตาม'?'waiting':'doing';return `<em class="${c}">${esc(s)}</em>`}
function dashboard(){title.textContent='Dashboard';content.innerHTML=`<section class="cards"><div class="card"><span>งานทั้งหมด</span><b>${tasks.length}</b><small>รายการ</small></div><div class="card"><span>กำลังดำเนินการ</span><b>${tasks.filter(x=>x.status==='กำลังดำเนินการ').length}</b><small>งาน</small></div><div class="card"><span>รอติดตาม</span><b>${tasks.filter(x=>x.status==='รอติดตาม').length}</b><small>งาน</small></div><div class="card"><span>เสร็จสิ้น</span><b>${tasks.filter(x=>x.status==='เสร็จสิ้น').length}</b><small>งาน</small></div></section><section class="grid"><div class="panel"><div class="panel-title"><h2>งานล่าสุด</h2><a onclick="show('tasks')">ดูทั้งหมด →</a></div>${taskTable(4)}</div><div class="panel"><div class="panel-title"><h2>ความก้าวหน้าตามกลุ่มงาน</h2></div>${bars()}</div></section>`}
function taskTable(n=99,list=tasks){if(!list.length)return '<div class="empty">ยังไม่มีงาน</div>';return `<table><thead><tr><th>งาน</th><th>กลุ่มงาน</th><th>ผู้รับผิดชอบ</th><th>กำหนดส่ง</th><th>สถานะ</th><th></th></tr></thead><tbody>${list.slice(0,n).map(t=>{const i=tasks.indexOf(t);return `<tr><td>${esc(t.name)}</td><td>${esc(t.module)}</td><td>${esc(t.owner)}</td><td>${esc(t.due||'-')}</td><td>${badge(t.status)}</td><td><button onclick="removeTask(${i})">ลบ</button></td></tr>`}).join('')}</tbody></table>`}
function tasksPage(){title.textContent='งานทั้งหมด';content.innerHTML=`<section class="panel"><div class="panel-title"><h2>รายการงาน</h2><button class="primary" onclick="newTask()">＋ เพิ่มงาน</button></div><div class="search"><input id="search" placeholder="🔎 ค้นหาชื่องาน / ผู้รับผิดชอบ" oninput="filterTasks()"></div><div id="taskList">${taskTable()}</div></section>`}
function filterTasks(){const q=document.getElementById('search').value.toLowerCase();document.getElementById('taskList').innerHTML=taskTable(99,tasks.filter(t=>(t.name+' '+t.owner+' '+t.module).toLowerCase().includes(q)))}
function bars(){return modules.slice(0,7).map((m,i)=>`<div class="bar"><label><span>${m}</span><b>${progress[i]}%</b></label><div class="track"><div class="fill" style="width:${progress[i]}%"></div></div></div>`).join('')}
function modulesPage(){title.textContent='13 กลุ่มงาน';content.innerHTML=`<section class="panel"><div class="modules">${modules.map((m,i)=>`<div class="module" onclick="moduleTasks(${i})"><b>${String(i+1).padStart(2,'0')}. ${m}</b><span>ความก้าวหน้า ${progress[i]}% · ${tasks.filter(t=>t.module===m).length} งาน</span></div>`).join('')}</div></section>`}
function moduleTasks(i){title.textContent=modules[i];const list=tasks.filter(t=>t.module===modules[i]);content.innerHTML=`<section class="panel"><div class="panel-title"><h2>งานในกลุ่มงานนี้</h2><button onclick="show('modules')">← กลับ</button></div>${taskTable(99,list)}</section>`}
function calendar(){title.textContent='ปฏิทินงาน';content.innerHTML=`<section class="panel"><div class="panel-title"><h2>กำหนดส่งงาน</h2></div>${tasks.filter(t=>t.due).sort((a,b)=>a.due.localeCompare(b.due)).map(t=>`<div class="bar"><label><span>${esc(t.due)} · ${esc(t.name)}</span>${badge(t.status)}</label></div>`).join('')||'<div class="empty">ยังไม่มีงานที่กำหนดวันส่ง</div>'}</section>`}
function kpi(){title.textContent='KPI';content.innerHTML='<section class="panel"><div class="kpi"><div><b>86%</b><span>บรรลุเป้าหมาย</span></div><div><b>13</b><span>กลุ่มภารกิจ</span></div><div><b>34</b><span>ตัวชี้วัด</span></div></div></section>'}
function reports(){title.textContent='รายงาน';content.innerHTML=`<section class="panel"><div class="panel-title"><h2>สรุปผลการดำเนินงาน</h2><button onclick="window.print()">🖨️ พิมพ์ / PDF</button></div><p>งานทั้งหมด ${tasks.length} รายการ | เสร็จสิ้น ${tasks.filter(x=>x.status==='เสร็จสิ้น').length} | กำลังดำเนินการ ${tasks.filter(x=>x.status==='กำลังดำเนินการ').length} | รอติดตาม ${tasks.filter(x=>x.status==='รอติดตาม').length}</p>${taskTable()}</section>`}
function settings(){title.textContent='ตั้งค่าระบบ';content.innerHTML='<section class="panel"><h2>ตั้งค่าระบบ</h2><p>ข้อมูลรุ่นนี้จัดเก็บในเบราว์เซอร์ของเครื่องผู้ใช้</p><button onclick="if(confirm(\'ล้างข้อมูลทั้งหมด?\')){localStorage.removeItem(\'pcTasks\');location.reload()}">ล้างข้อมูลการทดลอง</button></section>'}
function show(page){document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.dataset.page===page));({dashboard,tasks:tasksPage,modules:modulesPage,calendar,kpi,reports,settings}[page]||dashboard)()}
document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>show(a.dataset.page));
function newTask(){document.getElementById('taskModule').innerHTML=modules.map(m=>`<option>${m}</option>`).join('');document.getElementById('modal').classList.remove('hidden')}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
document.getElementById('taskForm').onsubmit=e=>{e.preventDefault();tasks.unshift({name:taskName.value.trim(),module:taskModule.value,owner:taskOwner.value.trim(),due:taskDue.value,status:taskStatus.value,detail:taskDetail.value.trim()});save();closeModal();show('tasks');e.target.reset()}
function removeTask(i){if(confirm('ยืนยันลบงานนี้?')){tasks.splice(i,1);save();show('tasks')}}
show('dashboard');
